### ISSUE TITLE
Final report link 404s

### ISSUE THREAD

**Issue by annesteenbeek** [rkmcdonnell/PiksiLand#1]
I was searching for a bit more information on your project and I was hoping to be able to read the entire paper. Would it be possible to restore the dropbox file or could I get a copy?

**Comment by nickaragua22** [comment]
Sorry about that, accidentally deleted the file from Dropbox. The link should work now. Let us know if you have any more questions. 

Best,
Nick

**Comment by annesteenbeek** [comment]
Awsome, thanks.
